### ISSUE TITLE
New install - timeout exception

### ISSUE THREAD

**Issue by kubeworkz** [RootSoft/algoland#3]
Hi:
I just did a fresh install on a Ubuntu 18.04 box and I seem to be getting the following error:

```
Rootsoft\Algorand\Exceptions\AlgorandException
{"message":"Request Timeout"}
http://localhost/explore
```

From what I can tell the ExploreController is trying to search for some stuff upon starting the app. I popped into the docker: `algoland_laravel.test_1` and everything is listening on port 80. All looks good. Is there something I'm missing on my local box that's required? (i.e. do I need to connect to an indexer etc...) I have ipfs, docker desktop, and all the requirements installed. I'm fairly familiar with Laravel. Any pointers greatly appreciated. 

Cheers, Dave

**Comment by RootSoft** [comment]
hi @kubeworkz 

It looks like some rounds (time) have passed since the initial deployment of this tutorial (round: 13387750) and now (round: 17505360). You can get the current round using `Algorand::status()`.

I've just tested it and we get a 'Request Timeout' because it takes too long for the API (AlgoExplorer) to fetch all data from the blockchain within the given timeframe, hence the request timeout is thrown.

A solution would be to increase the `afterMinRound` in `ExploreController` to a higher value (e.g the current round).
An optimal solution would be to host your own node and improving the queries/indexes.

Here is some more information about the issue: https://github.com/algorand/indexer/issues/202

**Comment by kubeworkz** [comment]
Thanks a lot - I'll check out these suggestions and let you know how it goes. Cheers, Dave

**Comment by kubeworkz** [comment]
Bumping up the time worked like a charm. Thanks again.
