### ISSUE TITLE
Dumb Newbie Algo Question

### ISSUE THREAD

**Issue by kubeworkz** [RootSoft/algoland#4]
Hi:
Now that IPFS is working on Ubuntu I got a little further. I now get the following message error:

```
{"message":"TransactionPool.Remember: transaction J7A6SO5JPIZ2VELLXAA3BSGRPREQDTSMPO4JJS4QGM34PKVV5ORA: overspend (account HRLDFVM57ZLDEECQJZI5YAWXT33LLZ5JCC4QTMJFVD323DTQUGLUAH5PRQ, data {_struct:{} Status:Offline MicroAlgos:{Raw:0} RewardsBase:0 RewardedMicroAlgos:{Raw:0} VoteID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] SelectionID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] VoteFirstValid:0 VoteLastValid:0 VoteKeyDilution:0 AssetParams:map[] Assets:map[] AuthAddr:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ AppLocalStates:map[] AppParams:map[] TotalAppSchema:{_struct:{} NumUint:0 NumByteSlice:0} TotalExtraAppPages:0}, tried to spend {1000})"}
```
It appears I'm trying to spend something. Now comes the dumb part - do Algos need to be present in my wallet to make this happen? If so, what's the minimum....Cheers, Dave

**Comment by RootSoft** [comment]
In order to make transactions on the Algorand network, you need to pay small fees, and have the available amount in your wallet/account. On MainNet, you can buy Algo from exchanges, but since we are on TestNet, you can dispense Algos from a dispenser. Just fill in your Algorand address [here](https://bank.testnet.algorand.network/) and wait until they are available on your account.

You can easily track transactions, accounts, balances, ... with [AlgoExplorer](https://testnet.algoexplorer.io/) and fill in the transaction id, Algorand addresses, etc.

There is some more information [here](https://developer.algorand.org/solutions/build-and-deploy-your-nfts-with-laravel-ipfs) in the **funding our account** section.

I highly recommend joining the [Algorand Discord](https://discord.com/invite/84AActu3at). There are tons of developers helping out and we got a PHP-sdk channel as well. 😄

**Comment by kubeworkz** [comment]
Cool, all good. Just did my first mint. Is there a way to find my file on IPFS? Can't seem to find the CID anywhere...
Cheers,
Dave

**Comment by RootSoft** [comment]
Not sure how you can find the CID with the IPFS CLI, however the CID should be encoded in the note transaction field when minting the NFT.

**Comment by kubeworkz** [comment]
Ah, perfect. Found it in the Algo Explorer. Thanks for all the help. Cheers, Dave
